server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swrp_development
    username: swrpapp
    password: u4Hz5c32$0LW

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
